#!/usr/bin/env python
"""Write splits/README.md and reports/gate_a_data.md from the generated manifests."""
import json
from collections import Counter

from auditbench_harbor.cli import GROUPS, INVENTORY, LABELS_DIR, UNITS_DIR, VERSIONS
from auditbench_harbor.paths import REPO_ROOT, SPLITS_DIR
from auditbench_harbor.windows import load_units


def table(rows, header):
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def main() -> None:
    versions = json.load(open(VERSIONS))
    inventory = json.load(open(INVENTORY))
    groups = json.load(open(GROUPS))["groups"]
    alloc = json.load(open(SPLITS_DIR / "allocation.json"))
    edges = [json.loads(line) for line in (SPLITS_DIR / "group_edges.jsonl").read_text().splitlines()]
    labels_summary = json.load(open(LABELS_DIR / "summary.json"))
    units = {s: load_units(UNITS_DIR / f"{s}.jsonl") for s in ("train", "dev", "test")}

    edge_rules = Counter((e["rule"], e["strength"]) for e in edges)
    cells = alloc["counts"]["task_label"]
    unit_rows = []
    for s in ("train", "dev"):
        c = Counter((u.task, u.label) for u in units[s])
        g = Counter((u.task, u.label, u.group_id) for u in units[s])
        gi = Counter((t, label) for (t, label, _) in g)
        for (t, label), n in sorted(c.items()):
            unit_rows.append((s, t, label, n, gi[(t, label)]))
    test_units = len(units["test"])

    readme = f"""# Splits

Generated by `auditbench-harbor provenance|split|labels|units` from AuditBench commit
`{versions['auditbench']['commit']}` (dirty: {versions['auditbench']['dirty']}). Do not edit by hand.

## Provenance groups

{len(inventory)} files form **{len(groups)} connected groups** under the strong edge rules below
(weak campaign-day edges are recorded in `group_edges.jsonl` but not used for grouping; `--include-weak`
reproduces the alternative). Every edge carries its rule and evidence.

{table(sorted(edge_rules.items()), ["rule / strength", "edges"])}

Multi-scenario groups: {", ".join(f"`{g['group_id']}` ({len(g['scenario_keys'])} scenarios, tasks {','.join(g['tasks'])})" for g in groups if len(g['scenario_keys']) > 1)}.

## Allocation

Seed `{alloc['seed']}`, ladder `{alloc['ladder']}`, chosen fractions `{alloc['chosen_fractions']}`,
feasible: **{alloc['feasible']}**. Constraints: dev >= {alloc['constraints']['min_dev_groups_per_task_and_label']} positive and
{alloc['constraints']['min_dev_groups_per_task_and_label']} benign groups per task; train >= {alloc['constraints']['min_train_positive_groups_per_task']} positive groups per task.
Realised group counts: {alloc['counts']['groups']} (dev exceeds 10% because the constraints bind; this is the recorded deviation).

{table([(k, v.get('train', 0), v.get('dev', 0), v.get('test', 0)) for k, v in sorted(cells.items())], ["task / label (groups)", "train", "dev", "test"])}

Dataset: {alloc['counts']['dataset']}. OS: {alloc['counts']['os']}.

## Canonical units (windows / files) and independent groups

{table(unit_rows, ["split", "task", "label", "units", "groups"])}

Test: {test_units} units, **sealed** (no model runs, oracle scoring, or prompt/reward tuning; builds require `--allow-test` and `AUDITBENCH_ALLOW_TEST=1`).

## Label audit

Train/dev target units: {labels_summary['train']['by_status']} / {labels_summary['dev']['by_status']}. Test: {labels_summary['test']['by_status']}.
Unplaced annotations: {labels_summary['unplaced']}.

## Limitations

- Few independent scenarios: the largest OpTC group (`g:optc/h501_attack-scenario3`) spans four tasks; exfiltration has only
  {cells['exfiltration/attack']['train']} positive train groups.
- Host-held-out and attack-template-held-out generalisation are not established by this split; Lab Linux scenarios share one host.
- Evidence support is a deterministic record match (timestamp at annotation precision + entity/indicator), not a human audit; the
  manifests in `manifests/labels/` are meant to be reviewed before freezing.
- Benign windows carry no annotations; a window without a target is not proof of benign activity.
"""
    (SPLITS_DIR / "README.md").write_text(readme)

    inv = versions["inventory_summary"]
    report = f"""# Gate A: data, provenance, labels, splits

Status: generated and checked locally on the AuditBench checkout `{versions['auditbench']['commit'][:12]}`; model-blind.

- Inventory: {inv['files']} files, {inv['distinct_contents']} distinct contents, {inv['byte_identical_groups']} byte-identical groups,
  {inv['scenario_keys']} dataset-qualified scenario names; nominal chunks {inv['by_source']}; timestamp parse failures {inv['parse_failures_total']},
  non-monotonic records {inv['nonmonotonic_total']}. All times are reduced with explicit timezones (`grader/timestamps.py`).
- Provenance: {len(edges)} edges, {len(groups)} groups (plan's preliminary estimate was 49 components before campaign review; OpTC
  same-host-same-day links reduce it further).
- Split: see `splits/README.md`.
- Labels: every train/dev annotation unit is `supported_positive`; five OpTC lm-scenario2 hosts (multicast/broadcast/link-local)
  are `ambiguous` and sit in the sealed test split; Lab lm-scenario3 has no file and a placeholder entity (unplaced).
- OpTC LM uses the unique-host convention (records merged by external host); persistence records with several technique names
  become one target unit per technique sharing the candidate timestamps.

Open items before freezing (PREREG.md): human review of `manifests/labels/{{train,dev}}.jsonl` evidence lines and of the
negative attack-file windows sample; decision on OpTC campaign-day (weak) edges; decision on the thin exfiltration train cell.
"""
    (REPO_ROOT / "reports" / "gate_a_data.md").write_text(report)
    print(readme[:1500])


if __name__ == "__main__":
    main()
